### PR TITLE
WIP : Fix for OSS issues and a couple of bug fixes

### PR DESCRIPTION
**Pull request by dan-dr**
* Add custom setting `codeCliPath` for OSS users
* Add usage of the documented `useCliBaseInstallation`
* Fix removing and adding extensions without cli to use lowercase pacakage names

#### Short description of what this resolves:
Fixes issue where the extensions didn't sync under the OSS variant of VS Code.
The problem seemed to stem from the inability of the extension to find the cli of VS Code.

#### Changes proposed in this pull request:
- Let users set the cli path of VS Code in the extension local settings
- Let users disable installation using the `useCliBaseInstallation` settings - which was documented but not used anywhere - which also fixes OSS issues (depending on the next listed change)
- Force installation and deletion of extensions **without cli** to use lowercase folder paths for the extension paths, otherwise VS Code might not recognize the extension is installed, or the extension my not be removed if installed manually.

**Fixes**: #668 

#### How Has This Been Tested?
Ran this on my local dev machine (Solus Linux) where downloading and removing extensions didn't work at all using the OSS variant of VS Code.

Performed multiple installs, uninstalls, uploading and downloading of settings.
Without manually editing the new custom settings, the extension behaves exactly the same, so users who do not have issues will continue normally.

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [x] My change requires a change to the documentation and Github Wiki.
- [x] I have updated the documentation and Wiki accordingly.
- [ ] Test with existing Non OSS versions.

### CODE REVIEW

**Comment by shanalikhan** [comment]
> Ran this on my local dev machine (Solus Linux) where downloading and removing extensions didn't work at all using the OSS variant of VS Code.

As you have tested this in your machine with OSS version of code.

Can you test it also for Standard, and portable version for code so we make sure it doesnt break on the existing versions of code?

**Comment by tristan957** [comment]
@dan-dr have you tested on Windows yet?

**Comment by knobhead** [comment]
this surely would be a nice christmas gift :-) :christmas_tree:

**Comment by shanalikhan** [comment]
Yes, I will release new version. Once its been tested for Non OSS versions of code ( to make sure it doesnt break existing) also like tested for OSS versions.

**Comment by tristan957** [comment]
What is the status of this?

**Comment by ptMuta** [comment]
Soo.. Abandoned? :/

**Comment by sarpik** [comment]
I can try to test this on windows 10 & arch linux today or tommorow.

**Comment by shanalikhan** [comment]
Closing this PR.
Reason : https://github.com/shanalikhan/code-settings-sync/issues/668#issuecomment-477145620

**Pull request closed without merging**
