### PR TITLE
Add support for disabled extensions

### PR DESCRIPTION
**Pull request by r-inaldi**
#### Short description of what this resolves:

Takes account disabled extensions when uploading or downloading the gist file.

#### Changes proposed in this pull request:

- `CreateExtensionList` now uses `code --list-extensions` to get enabled and disabled extensions;
- When `download` executes it verifies the extension object's enabled property . If false calls `code --disable-extension` with the extension name.

**Fixes**: #143 

#### How Has This Been Tested?

Tested on a Macbook with VSCode.

- Open `code-settings-sync` project;
- Disable an extension; 
- While debugging (`F5`) inside this branch execute `Upload / Update settings`;
- Then check in your gist if the current extension is disabled;
- Leave the debugging mode and uninstall the same extension;
- Open the debugging mode and execute `Download settings`;
- Check if it installs the extension and disables it automatically.

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [ ] My change requires a change to the documentation and GitHub Wiki.
- [ ] I have updated the documentation and Wiki accordingly.

### CODE REVIEW

**Comment by mjmardini** [comment]
Please look into this @shanalikhan. Thank you for this extension. Also thank you for your effort @lcsrinaldi.

**Comment by shanalikhan** [comment]
Give me some time , a two weeks or three.
Need to merge other code PR before reviewing and merging this.

**Comment by Kurtz1993** [comment]
Any updates on this PR status? 😃  I'd love to have this feature.

**Comment by shanalikhan** [comment]
https://github.com/microsoft/vscode/issues/15466
Please upvote and comment over there. Using API instead of CLI is more feasible. 

Settings Sync use API to install/uninstall all the extensions from the v3.3.0

**Comment by richcocoa** [comment]
Wouldn't it be better if we have support for this using the CLI available while we wait for API to materialize? Also the vscode team hasn't assigned a proper milestone for the feature request. So it is not a priority for them right now. Does the PR need any changes to be useful enough to be merged? Would be glad to give it a try.

**Comment by arnohovhannisyan** [comment]
@richcocoa The problem is that we can't easily find the CLI. There are so many variants of VSCode that it would be inefficient/impossible to hardcode them. That's why we're trying to use the API.

**Comment by r-inaldi** [comment]
I don't understand what's the problem of using the CLI.

As you can see here https://github.com/shanalikhan/code-settings-sync/blob/v3.2.9/src/service/pluginService.ts#L302

The code was already using the command line to install other extensions.

**Comment by arnohovhannisyan** [comment]
@r-inaldi Yes, but coverage is spotty with the CLI method. It's a pain getting the code executable when there are versions of code, like code-server and vscodium, that have different binaries. Also, Windows, macOS, and Linux all have the executables in different places.

**Comment by shanalikhan** [comment]
@r-inaldi 
Actually, CLI based commands are going to remove in the upcoming version.
I have asked code team, lets see what they respond, else what i think for the temporary solution will be we will use disabling and enabling them via CLI (considering the CLI based things wont work on OSS).

I am keeping this PR open.

**Comment by shanalikhan** [comment]
@r-inaldi

We can use CLI based commands for disabling and enabling the extensions. 

We can release this PR in `v3.4.0`. Currently the CLI based methods are removed from the code in favor of API to install / uninstall extensions.

This feature will be `disabled` by default using Global Settings Configuration and needs to be enable to allow user to disable/enable extension with the warning that it doesn't support OSS versions.

**Comment by shanalikhan** [comment]
Let me know when you fix it, I will merge the PR.

**Comment by r-inaldi** [comment]
@shanalikhan 

I don't know what you want me to do here. Fix what? Not sure how to proceed.

**Comment by shanalikhan** [comment]
We are now using API to perform functions that were previously using VSCode Command lines interface. (e.g installing extensions). Because we were unable to identify the `code` command line path for code OSS versions.
If you look into the latest version you will see, Settings Sync doesnt use command line to install extensions.

Enable / Disable Extension doesn't have API ( that i have asked on https://github.com/microsoft/vscode/issues/15466) hence you need to introduce the command line in extension back again to perform enable / Disable extensions only.

Let me know if you have any confusion. You will find the code related to running command lines in releases prior to v3.3

**Comment by r-inaldi** [comment]
Oh cool, thanks for explaining! I'll make this changes when I have some time. 

Do you also want me to add an option to enable this in the extension settings?

**Comment by shanalikhan** [comment]
> This feature will be disabled by default using Global Settings Configuration and needs to be enable to allow user to disable/enable extension with the warning that it doesn't support OSS versions.

Yes.

**Pull request closed without merging**
