### PR TITLE
Fix #754 and #865

### LINKED ISSUE #754: Updating when nothing has changed
🐛 **Describe the bug**  
When you change a value of a setting property that has   `// @sync-ignore` on it, it will still update.  So if you do it a lot, you end up with a gist history like this... 

`@userName userName revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
  
2  cloudSettings
@@ -1 +1 @@
{"lastUpload":"2019-01-20T23:35:15.940Z","extensionVersion":"v3.2.4"} 	{"lastUpload":"2019-01-20T23:35:31.712Z","extensionVersion":"v3.2.4"} 
 @userName userName revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
  
2  cloudSettings
@@ -1 +1 @@
{"lastUpload":"2019-01-20T23:35:04.064Z","extensionVersion":"v3.2.4"} 	{"lastUpload":"2019-01-20T23:35:15.940Z","extensionVersion":"v3.2.4"} 
 @userName userName revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
  
2  cloudSettings
@@ -1 +1 @@
{"lastUpload":"2019-01-20T23:35:00.152Z","extensionVersion":"v3.2.4"} 	{"lastUpload":"2019-01-20T23:35:04.064Z","extensionVersion":"v3.2.4"} 
 @userName userName  revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
  
2  cloudSettings
@@ -1 +1 @@
{"lastUpload":"2019-01-20T23:34:56.838Z","extensionVersion":"v3.2.4"} 	{"lastUpload":"2019-01-20T23:35:00.152Z","extensionVersion":"v3.2.4"} 
 @userName userName  revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
`

The only change that is being uploaded is a change to date/time.  I change my ignored setting dozens of times per day, so my Gist log looks crazy.  It's a lot of unnecessary uploading.  Could you make it so the anything with a  `// @sync-ignore`  doesn't trigger an upload?  Thank you very much for this awesome tool.

### PR DESCRIPTION
**Pull request by ioprotium**
#### Short description of what this resolves:
Fix #754 and #865

Only my commits as requested

### CODE REVIEW

**Comment by shanalikhan** [comment]
can you solve the conflicts so i can merge it ?

**Comment by shanalikhan** [comment]
Same fix merged for the PR #877.
You might need to test this after rebasing and solving the conflicts 
https://github.com/shanalikhan/code-settings-sync/pull/877/files#diff-a3281403b8563f0dc6c841b4f197c14dR242

**Comment by ioprotium** [comment]
@shanalikhan have you added pragma support to other files? If yes I should add code for those files too.
Changes from #877 on file **pragmaUtil.ts** can be taken. For the **sync.ts** I suggest to leave my changes until I drop another PR for the other setting files (FILE_KEYBINDING_MAC, FILE_KEYBINDING_DEFAULT). Let me know what do you think.

**Comment by shanalikhan** [comment]
> have you added pragma support to other files? If yes I should add code for those files too.

Yes, PR https://github.com/shanalikhan/code-settings-sync/pull/854 has been merged in `v3.3.0` branch that includes the support for pragmas for `keybindings.json` as well.

You can test it on your machine and improve the scenario for it as well if you think we can improve.

**Comment by fgallardograzio** [comment]
@ioprotium Is it possible that the changes you introduced related to #754 are causing the extension to **remove** the `settings.json` file from the gist when the user manually runs the "Sync: Update / Upload Settings" command without changing said file?

**Comment by ioprotium** [comment]
@shanalikhan then I will add code for those files. We need to define integration test for the whole process, from the file changes detection to the upload. Do you have any ideas to accomplish it?

@fgallardograzio It may causes to not upload the file in some scenario. Please wait to may next PR I will check this.

**Comment by shanalikhan** [comment]
> We need to define integration test for the whole process, from the file changes detection to the upload. Do you have any ideas to accomplish it?

Settings Sync use chokidar in the backend to detect the file change, what we can do it to see if they provide options to see the trail of file contents that are changed.

**Comment by ioprotium** [comment]
@shanalikhan there is still work to do in order to add support to the other files.
Wait for my next PR

**Comment by shanalikhan** [comment]
ok let me know once it is ready to merge for the fixes #754 and #865

**Comment by shanalikhan** [comment]
@ioprotium any idea when you can fix this two issues?

**Comment by ioprotium** [comment]
@shanalikhan I'll try to fix them tomorrow. But basically, if you added support for pragmas in every file, we need a local copy of each file to check when they actually change. Besides that I think there is an issue: if the file is not uploaded is deleted from the gist?

**Comment by arnohovhannisyan** [comment]
@ioprotium

> if the file is not uploaded is deleted from the gist?

Yes, I have experimented with this before and can confirm this.

**Comment by ioprotium** [comment]
@arnohovhannisyan @shanalikhan well, then we should verify for each file. If one or more have changed, we need to upload every file.

**Comment by ioprotium** [comment]
@shanalikhan I've solved the file conflict but project will still be broken.
This weekend I'll add more commits to this PR or create a new one. I'll let you know

**Comment by ioprotium** [comment]
@shanalikhan my last commits fix the problem. I've noticed that the extension was already getting the gist before uploading the files. So I compare against the remote files. The entire gist will be updated if one or more local files have changed.

Note:
- I couldn't get yarn run test working. I get the "Can't find vscode module". Launch test is also broken
- I added a fix for typing from octokit.

To have in mind:
- Sync.ts is getting big, unreadable and in consequence unmaintainable

This PR is ready to be merge.

**Comment by arnohovhannisyan** [comment]
@ioprotium

> Sync.ts is getting big, unreadable and in consequence unmaintainable

I was actually thinking of refactoring `sync.ts` + some other long files into separate files after `v3.3.0` gets released.

**Comment by ioprotium** [comment]
@arnohovhannisyan cool!

**Comment by ioprotium** [comment]
@shanalikhan I'd try to become a more active collaborator, I think we can improve it taking into account all user's suggestion. This pragma util turns out to be an alternative to github versioning of the settings, since you only have to specify which settings should be applied to your dev environment. 

I'll take a loot at the open issues when I find time.

**Comment by shanalikhan** [comment]
@ioprotium 
Thanks for the fix. The Pragma Util has become the best choice for the users dealing with the Github GIST since it covered alot of scenarios. 

Feel free to improve. I might release new version this week.
Also if you think we can improve the public wiki for Pragma Util, you can improve that.

**Pull request merged**
