### PR TITLE
Fix #1010

### LINKED ISSUE #1010: Webview does not set a content security policy
Hi, I'm the developer of VS Code's webview API. I noticed that your extension seems to create a webview that does not set a [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). All webviews (even very simple ones) should set a content security policy. This helps limit the potential impact of content injections and is generally a good measure for defense in depth. 

We've documented how to add a content security policy to VS Code webviews [here](https://code.visualstudio.com/api/extension-guides/webview#content-security-policy). Please  add the most restrictive content security policy possible to your webview. I am not aware of any immediate security issues with your extension but having a restrictive content security policy is important to help protect users of your extension.

---

*Also note that in development mode, in VS Code 1.38 you should also see a warning if you create a webview that does not set a content security policy: https://github.com/microsoft/vscode/issues/79248*

### PR DESCRIPTION
**Pull request by ParkourKarthik**
#### Short description of what this resolves:
Resolves security issues with content security policy 

#### Changes proposed in this pull request:
Added content security policy for webviews

**Fixes**: #1010 

#### How Has This Been Tested?
Verified that there is no view mismatch and console error logs.

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [ ] My change requires a change to the documentation and GitHub Wiki.
- [ ] I have updated the documentation and Wiki accordingly.

### CODE REVIEW

**Comment by ParkourKarthik** [comment]
@shanalikhan  I've just modified the first page. Verify that if it is ok to update other pages similarly.
On your confirmation, I'll be updating the other Webviews accordingly within this PR.
I do have several doubts below:

1. To explicitly set values for different sources?
2. Is it safe to use 'unsafe-inline'? If not what is preferred, nonce or moving the inline scripts out if possible?

**Comment by shanalikhan** [comment]
> To explicitly set values for different sources?

Can you explain it.

> Is it safe to use 'unsafe-inline'? 

Yes lets keep this as of now unless code gives warnings or logs in console :)


Feel free to improve other webviews as well.

**Comment by ParkourKarthik** [comment]
I mean, right now I've set values to the default-src directive which serves as a fallback of other directives such as script-src, style-src, img-directive, etc.
Right now, the default-src is set with certain values so that the policy doesn't fail for the html page. But the values are applicable for all the csp directives.
For example, I've set 'unsafe-inline' in default-src which is to enable inline scripts in the code which is applicable in this landing page. But, this value would be a fallback value for other directives as well which may affect the security in some cases (I'm not sure though).

**Comment by ParkourKarthik** [comment]
I've updated the webviews as required. You can verify and merge the changes.

**Pull request merged**
