### PR TITLE
Support more languages

### PR DESCRIPTION
**Pull request by arnohovhannisyan**
#### Short description of what this resolves:
This PR adds support for 8 new languages to Settings Sync. 

#### Changes proposed in this pull request:

- Add support for 8 more languages
  - Spanish
  - French
  - Hungarian
  - Italian
  - Korean
  - Portuguese
  - Russian
  - Turkish

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.

> Note that these translations may not be 100% accurate and may need some revisions.

### CODE REVIEW

**Comment by arnohovhannisyan** [comment]
If anyone is wondering how I localized the package.nls.json file to many different languages, here you go: https://github.com/arnohovhannisyan/Localizer

**Comment by shanalikhan** [comment]
Merged, Thanks

**Comment by shanalikhan** [comment]
@arnohovhannisyan

There are alot of files present in root folder. Can you send me a PR that will move these languages files to any folder like `locals` and read the files from that folder.
What do you think ? Regarding folder name or any further improvement.
We can add this in v3.3.0

image

**Comment by arnohovhannisyan** [comment]
@shanalikhan Sure, I'll start as soon as possible.

**Comment by arnohovhannisyan** [comment]
@shanalikhan I have run into an issue while attempting to move the localizations to a different folder. VSCode seems to only check in the root folder for them, so the top-level menus like `Sync: Download Settings` and others are not translated. Do you know how to get around this?

**Comment by shanalikhan** [comment]
Oh!!!
I also have to look into this. You can ask vscode team about it or checkout the other extensions code.

**Comment by shanalikhan** [comment]
@arnohovhannisyan 
Can you update this wiki with the new languages or improve the process for new users to improve and add their languages.
https://github.com/shanalikhan/code-settings-sync/wiki/Add-or-Improve-Language-Support

With the total languages Settings Sync support and pending ones.

**Comment by arnohovhannisyan** [comment]
@shanalikhan I have updated the page to better fit the current status of the extension. However, I have also discovered an issue with the Portuguese localization file. The current name is `package.nls.pt.json`, while it should be `package.nls.pt-br.json` (according to [this](https://code.visualstudio.com/docs/getstarted/locales#_available-locales)). I will be submitting a PR shortly fixing this issue.

**Pull request merged**
