### PR TITLE
Landing Page: Don't Show This Again

### PR DESCRIPTION
**Pull request by arnohovhannisyan**
#### Short description of what this resolves:
This PR adds a button to not show the landing page, even if the extension is not configured.

#### Changes proposed in this pull request:

- Use `context.globalState` to keep track of preference
- Reset the preference when resetting extension settings
- Don't show the landing page if enabled

**Fixes**: https://github.com/shanalikhan/code-settings-sync/issues/959#issuecomment-511682067

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.

### CODE REVIEW

**Comment by shanalikhan** [comment]
Can you setup this configuration like the image

image

Position should be right-aligned to `Sponsors`. If you have any ideas than suggest.

**Comment by shanalikhan** [comment]
@arnohovhannisyan 
Can you fix it today so i can release new version.
Not getting good response from the users ( in emails, reviews etc)

**Comment by arnohovhannisyan** [comment]
@shanalikhan I should be able to finish it today, but it might take a while since I'm currently away from home.

**Comment by arnohovhannisyan** [comment]
@shanalikhan 

> If you have any ideas than suggest.

How about we put the checkbox pinned on the bottom right of the page. This way it's easily spotted. It also doesn't have anything to do with sponsors.

**Comment by shanalikhan** [comment]
Yes, go ahead. Do share the image.

**Comment by arnohovhannisyan** [comment]
@shanalikhan 

image

**Comment by shanalikhan** [comment]
@arnohovhannisyan 
There are some improvement that can improve the UX.
What are your views about it. We can ship these improvements with v3.4.1


1. On Startup
     When user click on Login with Github and click on `skip` button. There dialog should be appeared to user that GIST is not configured, Settings Sync will create new GIST on Upload.

2. On Upload
    When token and GIST is not configured, page does open along with the warning of invalid GIST.
     - Invalid GIST error should not appear when GIST is empty.
     - When user gets the token and select any gist. It should start the upload process automatically as User is coming from `On Upload` process.
     - If user click on `Skip` button, it should start the upload process create the new GIST as User is coming from `On Upload` Process.


3. On Download
    When token and GIST is not configured, page does open along with Invalid GIST error.
    - Invalid GIST error should not appear when GIST is empty.
    - When user gets the token
    - On Gist Page, `Skip` button should be hidden as user wants to download, instead we can show close button to stop the process.
    - When user select any GIST, it should start downloading process as user is coming from `On Download` process

**Comment by shanalikhan** [comment]
**Error:**

I have disabled the check.
Now when Settings sync isnot configured, on upload it doesnt open the configuration page to setup.

**Comment by arnohovhannisyan** [comment]
@shanalikhan 

> Transfer the Github Application ownership to my account

I have already initiated the transfer.

> Can you fix it when possible i'm looking to release new version.

Yes, I will create a PR soon

**Comment by shanalikhan** [comment]
> I have disabled the check. Now when Settings sync isnot configured, on upload it doesnt open the configuration page to setup, instead gives error of invalid token.

I have fixed this check.

You can include the things discussed here https://github.com/shanalikhan/code-settings-sync/pull/960#issuecomment-512782903 and one more thing in PR.

i-e
The `Show at startup` is always checked, we need to bind to its current value.

**Pull request merged**
