### PR TITLE
Use gulp to compile and minify code (#823)

### PR DESCRIPTION
**Pull request by arnohovhannisyan**
#### Short description of what this resolves:
Use gulp and gulp-typescript to transpile and minify (#823) the code. Gulp is very customizable and can be used for many things, not just transpiling. This implementation will be very useful for automating things later on.

#### Changes proposed in this pull request:

- Transpile, and minify the code using gulp and some plugins
- Generate source maps for each file

**Fixes**: 1

#### How Has This Been Tested?

I have tested this by compiling the code and running the extension, and it has worked. The files are also minified and all source maps are generated.

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.

#### It can:
- [x] Transpile
- [x] Minify
- [x] Generate source maps (for debugging)

### CODE REVIEW

**Comment by shanalikhan** [comment]
Lets keep webpack for now.
I problem is Settings Sync file was minified to around 700Kb in previous versions.
But currently webpack is adding source maps which makes size around 1.8Mb.

Can you fix the webpack building process so I can release the version?

**Comment by arnohovhannisyan** [comment]
Sure, I can try.

**Comment by arnohovhannisyan** [comment]
Ok, I just got the production file size to ~400kb

**Comment by shanalikhan** [comment]
I'm still getting 1.68Mb size.
Try using `vsce package`

**Comment by arnohovhannisyan** [comment]
On the VSIX, I'm getting 850kb

**Comment by arnohovhannisyan** [comment]
I looked inside the VSIX using 7-zip, and the node_modules folder was in there. I think that's causing the high file size.

**Comment by arnohovhannisyan** [comment]
After adding node_modules and some other unnecessary files/folders to the .vscodeignore file, I got the VSIX to 150kb

**Pull request merged**
