### PR TITLE
Join a new service provider gitee

### PR DESCRIPTION
**Pull request by fanlide**
#### Short description of what this resolves:

Github access is slow in China, preferring to choose gitee.

#### How Has This Been Tested?

"gitServer": "gitee"

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [x] My change requires a change to the documentation and GitHub Wiki.
- [ ] I have updated the documentation and Wiki accordingly.

### CODE REVIEW

**Comment by shanalikhan** [comment]
I dont want to use new service.
There is already #413 opened that allows repo sync which you can use for gitee in future.

**Comment by fanlide** [comment]
@shanalikhan Thank you for your reply. If I can, I want to release the version of gitee to the vscode extension synchronously. Is that okay?

**Comment by shanalikhan** [comment]
What we can do is:
You can decouple the existing githubservice as generic generic service for upload / download.
Once it is done, you need to write githubservice that will be used for github by using the existing github code.

After that you can create new folder for custom services where you can write your own service for `gitee` gists.
`gitee` users needs to run some command to build it using the `giteeservice` file, or we can provide custom builds for `gitee` that can be downloaded separately by providing the link from the readme.

**Comment by fanlide** [comment]
Thank you very much for your advice. I currently add the `gitServer` parameter to the configuration file to switch services. If you don't use configuration parameters, it's also nice to use a separate build!

Can I merge these operations? Or just build it on my side.

**Pull request closed without merging**
