### PR TITLE
Update tutorial message (was outdated)

### PR DESCRIPTION
**Pull request by fr3fou**
Hi!

I noticed that on startup the tutorial message that pops-up points to an outdated link - http://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html

I updated it to point to the "proper" tutorial -
http://shanalikhan.github.io/2015/12/15/Visual-Studio-Code-Sync-Settings.html

### CODE REVIEW

**Comment by shanalikhan** [comment]
This is the tutorial for detailed settings configuration.
Can you point to this link
https://medium.com/@itsShanKhan/visual-studio-code-settings-sync-configurations-ed8dd6fd9753

**Comment by shanalikhan** [comment]
Thanks for noticing.
This is the tutorial for detailed settings configuration.
Can you point to this link
http://shanalikhan.github.io/2016/07/31/Visual-Studio-code-sync-setting-edit-manually.html

**Comment by fr3fou** [comment]
I updated it again with the proper link.

**Comment by shanalikhan** [comment]
Thanks

**Pull request merged**
