### PR TITLE
do not write `syncLocalSettings.json` if file has no change.

### PR DESCRIPTION
**Pull request by Cologler**
#363

### CODE REVIEW

**Comment by Stanzilla** [comment]
@shanalikhan any plans to merge and release this?

**Comment by shanalikhan** [comment]
@Stanzilla 
https://github.com/shanalikhan/code-settings-sync/issues/363#issuecomment-316042977
@Cologler informed that this PR didnt fix the problem for him, if this PR fixed problems for you, let me know i will release it.

**Comment by Cologler** [comment]
@shanalikhan The problem is `proper-lockfile` is cross process lock.

If start 2nd vscode process, the 1st vscode process will lose the lock because the 2nd run this code:
https://github.com/shanalikhan/code-settings-sync/blob/master/src/extension.ts#L29

`code-settings-sync` should be singleton instance on multi-process. 2nd vscode process should wait for lock instead of steal the lock from 1st vscode process.

**Comment by Cologler** [comment]
@shanalikhan This PR remove some unnecessary write disk operation. Just an optimization.

**Comment by shanalikhan** [comment]
Thanks, Merged ! @Cologler 
Will release new version tonight.

**Pull request merged**
