### PR TITLE
add support for xdg environment paths

### PR DESCRIPTION
**Pull request by Dennor**
This PR adds support too freedesktop XDG_DATA_HOME and XDG_CONFIG_HOME environment variables on linux platforms. This can be useful if VScode was installed for example from flatpak as config dir is in ${HOME}/.var/app/com.visualstudio.code/code/config and extensions are located at ${HOME}/.var/app/com.visualstudio.code/data/vscode/extensions.

### CODE REVIEW

**Comment by shanalikhan** [comment]
Thanks, will release this in upcoming version this week.

**Comment by shanalikhan** [comment]
meanwhile, it would be great if you resolve the conflicts and let me know when its ready.

**Comment by Dennor** [comment]
Done. If you need anything else, let me know.

**Comment by shanalikhan** [comment]
Released in v2.9.1
Thanks for your contribution
Let me know if you are willing to contribute in other features :)

**Pull request merged**
