### PR TITLE
WIP. Sync with Git Repositories

### PR DESCRIPTION
**Pull request by knyhle**
#### Short description of what this resolves:
Adding git sync. WIP. Requesting review.
- [x] 1. It should ask either backup needs to be saved on Github Gist or simple Git Repository.
- [x] 2. Once the User select the Git Repo, it should setup accordingly.
- [ ] 3. Provide user option to either use Github or GitLab and create a repository from there by their profile tokens.  
  - [x] Create Repository on Github
  - [ ] Create Repository on GitLab
- [x] 4. By Download means, user can do `git pull` forcefully. 
- [x] 5. By Upload means, user can do `git push` forcefully.
- [x] 6. Allow user to setup branches or profiles like `master` and `office` and keep the selected profile / branch in Sync Global Settings and download/ upload to that branch.
- [x] 7. When user is switched to Gist, it should not upload the Git folder there.
- [ ] 8. Support Github and Gitlab Enterprise versions

At the moment creating / pushing to different branches on github works.
Haven't wrote the gitlab service.
Will need to rework regex for enterprise versions probably.

#### Changes proposed in this pull request:
- WIP.

**Fixes**: #413 

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [x] My change requires a change to the documentation and GitHub Wiki.
- [ ] I have updated the documentation and Wiki accordingly.

### CODE REVIEW

**Comment by gudvinr** [comment]
Why do you need to access Github/Gitlab API directly? Wouldn't it be a lot more convenient to use just plain git interface using `git clone/pull/push/fetch/etc`?

Since you're heavily tying your implementation to limited number of services it won't allow it to use with your private Git repos (self-hosted or just local) and it _requires_ internet access to use synchronisation.

It doesn't solve issue in the way it was meant to be implemented.

**Comment by jordyvandomselaar** [comment]
I'm really excited about a feature like this, I really don't want my settings on a gist that can be found by anyone as it contains sensitive information.

**Comment by totkeks** [comment]
> I'm really excited about a feature like this, I really don't want my settings on a gist that can be found by anyone as it contains sensitive information.

The gists have always been private by default. Also your user's local vscode settings (`settings.json`) do not contain sensitive information by default.

**Comment by lizhuangs** [comment]
> > I'm really excited about a feature like this, I really don't want my settings on a gist that can be found by anyone as it contains sensitive information.
> 
> The gists have always been private by default. Also your user's local vscode settings (`settings.json`) do not contain sensitive information by default.

The gists have always been private by default.,however It can be seen by anyone who get the gist url.It is unsafe.

**Comment by jifalops** [comment]
Will this still require github access or will it also accept ssh urls like `git@github.com/user/repo`?

**Comment by shanalikhan** [comment]
Let me know if you want to work on it. I will reopen this PR

**Pull request closed without merging**
