### PR TITLE
V3.4.3

### PR DESCRIPTION
**Pull request by shanalikhan**
#### Changes proposed in this pull request:

-
-
-

**Fixes**: #

#### Checklist:

- [ ] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [ ] My change requires a change to the documentation and GitHub Wiki.
- [ ] I have updated the documentation and Wiki accordingly.

### CODE REVIEW

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
I'd like to ask support for resolving this issues.

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
I will be surprised if you can take the necessary steps.

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Need support

**Review by 5dwz5n6d7w-sudo — COMMENTED** [review]
Excited to use

**Pull request merged**
