### PR TITLE
Proposing new icon

### PR DESCRIPTION
**Pull request by BeardedBear**

### CODE REVIEW

**Comment by shanalikhan** [comment]
I tried this icon initially but it doesnt have better **contrast ratio** compared to current one.
If you have other good icons to suggest. Please do! I will change it.

**Comment by BeardedBear** [comment]
Okay, i can try with more contrast :)

**Comment by BeardedBear** [comment]
New try with more colorful icon :)
I can giving you the source of icon (.ai) if you want !

**Comment by shanalikhan** [comment]
Well, lets keep the current icon for now.

**Pull request closed without merging**
