### PR TITLE
Add upload and download gifs to readme (issue #423)

### PR DESCRIPTION
**Pull request by mmakarios**
I added the flow of the Upload and Download commands in gifs to the README, as requested in issue #423.

### CODE REVIEW

**Comment by shanalikhan** [comment]
Fantastic !
Thanks

**Comment by shanalikhan** [comment]
@mmakarios the upload image size is 9MB and it takes time to load, i tried to load from other repo also.
Would it be possible to compress the size

**Comment by mmakarios** [comment]
Sure, I managed to compress the upload gif to 4MB and the download gif to 1.4MB. Is that enough?

I need to submit a new pull request, right? Or can I change this one?

**Comment by shanalikhan** [comment]
You can open new pull request
Will github show the 4MB file in readme ? As currently it shows error when opening file

**Comment by mmakarios** [comment]
Apparently GitHub has a 10MB size limit for embed files, so the previous gif doesn't load. I will open the new PR.

**Pull request merged**
