### PR TITLE
Add language support- traditional chinese

### PR DESCRIPTION
**Pull request by YunChaoTsai**
#### Short description of what this resolves:

Add translation `traditional chinese`.

#### Changes proposed in this pull request:

- add `package.nls.zh-tw.json`

**Fixes**: #1028 

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [x] My change requires a change to the documentation and GitHub Wiki.
- [ ] I have updated the documentation and Wiki accordingly.

### CODE REVIEW

**Comment by YunChaoTsai** [comment]
Should I update this [page wiki/Add-or-Improve-Language-Support](https://github.com/shanalikhan/code-settings-sync/wiki/Add-or-Improve-Language-Support) before pull request merged?

**Comment by shanalikhan** [comment]
1. Have you checked the number of `keys` starting with `Sync :` should be equal to the other language files.
2. Can you post the screen shoots


Yes you can update the page once above verification steps are completed and this PR is ready to merge.

**Comment by shanalikhan** [comment]
PR is merged, you can update the wiki :)

**Comment by YunChaoTsai** [comment]
Thank you always.
I have updated the wiki.

**Pull request merged**
