### PR TITLE
fix: missing partial i18n translation

### PR DESCRIPTION
**Pull request by axetroy**

### CODE REVIEW

**Comment by shanalikhan** [comment]
As u have added new keys 
In this branch i have also merged PR to support German language 
It would be great if u can add the keys to the German language file  also

**Comment by shanalikhan** [comment]
Base branch has been changed to have those files

**Comment by axetroy** [comment]
@shanalikhan 
what should I do?

How could I add the keys to the German language file

**Comment by shanalikhan** [comment]
There are German keys available on other file.
Try pulling the pull request and see the file is available on your code repo as i have changed the base branch already.
Else yes you might need to sent PR (on base v3.1.0)

**Comment by axetroy** [comment]
@shanalikhan

yeah, I will close this PR and sent another base on v3.1.0.

But I don't know German. So the new key will be written in English until someone translates it.

**Comment by axetroy** [comment]
#593

**Pull request closed without merging**
