### PR TITLE
WIP: Diff viewer

### LINKED ISSUE #508: How to compare changes between local settings & remote settings?
**Visual Studio Code Version : 1.21.0
**Code Settings Sync Version : 2.9.0
**Operating System : Windows 10 x64 Pro
**Occurs On: not applicable
**Proxy Enabled: No
**GIst Id: 094e42e4a4ef3a34f8f35aaa163ba313

Before upload/download settings it would be useful to see changes in settings How to do it?

### PR DESCRIPTION
**Pull request by ParkourKarthik**
#### Short description of what this resolves:
Tries to resolve #508 

#### Changes proposed in this pull request:
- A new webview with list of files with changes.
- A new command to differentiate between local and cloud files.
- Introduced a cache mechanism for quicker access.

**Fixes**: #508 

#### How Has This Been Tested?
- Click `Sync:Download Settings` command
- Authorize in github
- Select gist to be downloaded
- In the diff summary page, click on `settings.json`

#### Screenshots (if appropriate):
image
image

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [x] My change requires a change to the documentation and GitHub Wiki.
- [ ] I have updated the documentation and Wiki accordingly.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

</details>

### CODE REVIEW

**Comment by ParkourKarthik** [comment]
@shanalikhan This is just a prototype. Let me know that this approach is ok to proceed with. I can clean up the required stuff later.

**Comment by shanalikhan** [comment]
Hi @ParkourKarthik 

Sorry for late reply. Lets discuss this in detail.

Can we make it a single page instead of two page currently as shown in image.
One page like summary page you have shown above only. Containing accordian like [here](https://getbootstrap.com/docs/4.3/components/collapse/#accordion-example) so user will only need to open the selected file and see the difference in each panel of accordian ( like in second image ). 

Sync all should be changed by `Proceed` button and rightly aligned with the heading `Settings With Sync Changes`

These are the above changes i have in mind :) and thanks for putting your time and effort in Settings Sync !

**Comment by ParkourKarthik** [comment]
@shanalikhan I agree with your suggestion of showing a single page by simplifying the view. But currently, I'm using the vscode's inbuilt fileComparer.
If we want to show like an accordion, we might have to manually build a comparing tool or use another 3rd party package for that. Maybe I could try to work on building a tool like that or you could suggest something to make use of.

**Comment by qrqhuang** [comment]
I'd like to see what changes before update/download.
So is there any progress for this pr ?

**Comment by shanalikhan** [comment]
@ParkourKarthik any update on the desired user scenario or may can open new file on button click that implement vscode own comparing two files in single tab option.

It would be great if you can implement that

**Comment by ParkourKarthik** [comment]
> @ParkourKarthik any update on the desired user scenario or may can open new file on button click that implement vscode own comparing two files in single tab option.
> 
> It would be great if you can implement that

Hey, sorry for the long gap. I did make use of inbuilt vscode comparer, but with some recent file path updates certain files comparison are broken.
Will first fix those and implement it. May be, we could decide upon implementing the single tab comparison option later.

**Comment by shanalikhan** [comment]
@ParkourKarthik

Hey, were you able to find some time to look into it. If its not possible i can close this PR for now and you can create new PR with the work done later when you can

**Comment by ParkourKarthik** [comment]
@shanalikhan Sorry, I did went through the code. But didn't have much time to work on it. I think you can close this and create a new one for someone to work on.

**Pull request closed without merging**
