### PR TITLE
Login with GitHub (WIP)

### PR DESCRIPTION
**Pull request by arnohovhannisyan**
#### Short description of what this resolves:
This PR allows the user to log in to GitHub using a button, and the extension will automatically generate a token with the correct scopes and find the gist id. (#506)

#### Changes proposed in this pull request:

- Login to GitHub using OAuth
- Create a GUI for Settings and Welcome page

**Improvements**: 2

#### How Has This Been Tested?

I have tested this by logging in to GitHub and checking if the token and gist id has been saved properly.

#### Screenshots (if appropriate):
image

image

image

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [x] My change requires a change to the documentation and GitHub Wiki.
- [x] I have updated the documentation and Wiki accordingly. (may need review)

#### Status:
- [x] Authenticate with OAuth
- [x] Save Token
- [x] GUI for Gist Selection page
- [x] GUI for Settings page
- [x] GUI for Welcome page

### CODE REVIEW

**Comment by shanalikhan** [comment]
Can you make similar UI like bookmarks extension
Release notes on left and on right side multiple buttons that will include Gibhub Login Button.
When login button is clicked, it can start process to get auth token.

How are you getting gist ID? from user detail. - is it by showing the list of gists available ?or user needs to setup gist manually.

**Comment by arnohovhannisyan** [comment]
Sure, I can try making a UI similar to that.

> How are you getting gist ID? from user detail.

I'm getting all the user's gists and checking to see which one has the cloudSettings file in it.

**Comment by arnohovhannisyan** [comment]
Does this look better?

image

**Comment by shanalikhan** [comment]
Yes its better.
For reference 
Check this image , needs to have all these things.

The background and the Settings Sync title and logo will persist on all the pages , home page , settings page or the github callback pages.
You can fill the sample release notes from latest version and put into here.
The bug can be light red and new feature will be like in the image.
Scroll bar added in both.

Buttons will be :
1. Login with Github
2. Edit Global Settings
3. Edit Environement Settings
4. Become a sponsor like above.


> I'm getting all the user's gists and checking to see which one has the cloudSettings file in it.

List can be shown with user to select from all gist which have `cloudSettings` in them alongwith gist title and let user select one of them.

image

**Comment by arnohovhannisyan** [comment]
Ok, I'll start working on that now.

**Comment by arnohovhannisyan** [comment]
> Edit Environment Settings

Is that the settings.json file?

**Comment by arnohovhannisyan** [comment]
> Become a sponsor

Where should that take you?

**Comment by shanalikhan** [comment]
> Is that the settings.json file?
If possible then navigate to Settings sync settings section from settings viewer.

>Where should that take you?

yes

**Comment by arnohovhannisyan** [comment]
Current progress:

image

Is there anything you want me to change?

**Comment by arnohovhannisyan** [comment]
I have updated the screenshots in the initial comment. If you want me to change anything, please tell me.

**Comment by shanalikhan** [comment]
I had posted an target image. Okay Let me give you detail when needs to be done for the page welcome page.

**Goal:** It should use same font and styling like the image i posted. I would request you to make a similar UI - exacltly the same.


1. **Title** should be same color, size and font with the **logo**. You can make a white cloud logo with the transparent background ( revert the current logo like in marketplace ) - Save as another file. - The title needs to be in the center of logo like th Bookmark ribbon logo and title place.
2. **Description** should be "Synchronize Settings, Snippets, Themes, File Icons, Launch, Keybindings, Workspaces and Extensions Across Multiple Machines Using GitHub Gist" - Same color, size and font.
3. **Below** to description you can add "by @shanalikhan" same size, color and font as description.


**Two columns** - Same style, font and size as reference image.
Scroll bar should be supported in both column - Check the reference image.


**Left Column** - Scrollable
1. Use same green button for "New" , light red button for "Fix" - Same size, button and color. Currently new and fix doesnt match - Please refer the reference document.
2. There is some difference in new and fix buttons and text
3. See link for PR , color size and font.

**Right Column** - Scrollable
1. Title **Configuration** - Same properties like "show your support"
Some **description** like "Please login via github to setup the Settings Sync or change configurations manually"
There should be two buttons after **description**
   a. Login with a Github
   b. Edit Configuration - ( Sorry initially i asked for two buttons) - Will further explain its work after this.

2. Title "Show Your Support" - Same properties like above.
  a. Same description for Settings Sync
  b. Same two buttons, PayPal button links to the URL in paypal button in readme.

Links - same properties.
1. Write a Review
2. Star Or Fork me on Github
3. Follow me on Twitter

3. Title "Sponsors"
Description - "Settings Sync Looking for sponsors to display here. Contact me on twitter or github."


Below to columns
Need Help ? Same as in image.
Same 2 links.


**Edit Configuration Page**

It will a two columns, the title, description and all things will be the stay on same location.
Only welcome page 2 columns and below it should be replaced with configuration page.

It should be two columns - Scrollable.
**Left Columns** - Title - "Environment Settings"
Add text boxes and checkboxes for each of the Settings Sync config present in `settings.json`.
Below to each of the configuration textbox, put settings description present in localization files.

**Right Column** - Scrollable
"Title - Global Settings"
All the custom json settings should be available like in above picture.


After these two columns.
There will be "Save" button in right side- When user clicks on save. Text should appear on left to the button that settings has been saved.


**Goal:** It should use same font and styling like the image i posted. 

Once the welcome and configuration page layout is completed, i will move to code review and github sync process.

Thanks

**Comment by arnohovhannisyan** [comment]
This is what I have so far:

Welcome:
image

Settings:
image

Gist selection:
image

Also:
1. I removed the "Save" button from the settings page because it was causing issues with the save process. Currently, it just displays some text saying "Saved!" whenever you make changes.
2. I haven't yet gotten to displaying the localized descriptions for the individual settings.

**Comment by shanalikhan** [comment]
Nice, let me know when you will be able to complete the checklist i have shared, I will provide you a detail review then.
Just for settings page, please add scroll bar with height allowed only vscode browser window viewport size.

**Comment by arnohovhannisyan** [comment]
Ok, I'll make those changes and let you know when I'm ready for review.

**Comment by arnohovhannisyan** [comment]
@shanalikhan Ok, I'm pretty sure I completed your checklist.

Here is the updated settings page:
image

**Comment by arnohovhannisyan** [comment]
@shanalikhan I'm going to create a fresh PR to resolve these conflicts and clean up the commit timeline.

**Pull request closed without merging**
