### PR TITLE
[WIP] Refactor

### PR DESCRIPTION
**Pull request by arnohovhannisyan**
#### Short description of what this resolves:
This PR separates different functionality into their own services to refactor the code.

#### Changes proposed in this pull request:

- Move `sync.ts` upload and download functionality and all gist functionality to `gist.service.ts`
- Move all settings-related functionality to `settings.service.ts`
- Move all output related functionality to `logger.service.ts`
- Move all auto-upload related functionality to `autoUpload.service.ts` 
- Move localization-related functionality to `localization.service.ts`
- Move initialization code to `init.service.ts`
- (probably more soon)

#### What definitely still works
- [x] Auto Upload
- [x] Settings GUI
- [x] OAuth Login
- [x] Gist Selection
- [x] Upload
- [x] Download
- [x] Public Gist
- [x] Ask Gist Name
- [x] Force Upload
- [x] Force Download

**Fixes**: #935 

#### How Has This Been Tested?

I have tested the functionality mentioned above, but it needs a lot more testing.

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.

WARNING: This is a **VERY EXPERIMENTAL** PR and has **LOTS** of changes (for developers. end-users shouldn't be affected).

### CODE REVIEW

**Comment by shanalikhan** [comment]
As per discuss with the author of #822. Following are the main objectives for refactoring.


1. "I think it’d be better if the interface is named `ISyncService` and only has the `upload` and `download` functions. That way, it’ll be a lot easier when implementing Git to just implement the `download` / `upload` functions and **use factory creation** to create the sync service"
2. There will be setting same thing named as `exportType` that should be set by default as "GithubGist" that will be future changed to either `Git`, `File`. 
3. Each export type will have their own settings we need to change the current `GithubGist` to new setting, hence the new settings will look like this.









Change the Global Settings like

```
{
    "ignoreUploadFiles": [
        "state.vscdb",
        "state.vscdb.backup",
        "syncLocalSettings.json",
        ".DS_Store",
        "sync.lock",
        "projects.json",
        "projects_cache_vscode.json",
        "projects_cache_git.json",
        "projects_cache_svn.json",
        "gpm_projects.json",
        "gpm-recentItems.json",
        "state.*"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "ignoreExtensions": [],
    "exportType" :"GitHubGist",
    "GitHubGist":{
        "gistDescription": "Visual Studio Code Settings Sync Gist",
        "token": "998a2ee5389f61d63d729ed62a261b1afaad8279",
        "downloadPublicGist": false,
        "openTokenLink": true,
        "lastUpload": "2019-06-24T16:18:55.696Z",
        "lastDownload": "2019-06-24T16:19:50.647Z",
        "githubEnterpriseUrl": null,
        "askGistName": false,
        "hostName": null,
        "autoUploadDelay": 20
    },
    "version": 340,
    "supportedFileExtensions": [
        "json",
        "code-snippets",
        "json2"
    ],
    "disableUpdateMessage": false,
    "customFiles": {},
    "universalKeybindings": false
}
```

**Comment by arnohovhannisyan** [comment]
@shanalikhan 

> only has the upload and download functions. That way, it’ll be a lot easier when implementing Git to just implement the download/upload functions.

I have also added `IsConfigured()` to the interface to make it easier to check if that service is configured properly.

---------------------

I was also thinking of removing some items from the `Advanced Options` menu because you can change them in the Settings UI and it would unclutter the settings service a lot.

```
"cmd.otherOptions.openSettingsPage",
"cmd.otherOptions.editLocalSetting",
"cmd.otherOptions.shareSetting",
"cmd.otherOptions.downloadSetting", **Can be toggled from Settings**
"cmd.otherOptions.toggleForceDownload", **Can be toggled from Settings**
"cmd.otherOptions.toggleForceUpload", **Can be toggled from Settings**
"cmd.otherOptions.toggleAutoUpload", **Can be toggled from Settings**
"cmd.otherOptions.toggleAutoDownload", **Can be toggled from Settings**
"cmd.otherOptions.toggleSummaryPage", **Can be toggled from Settings**
"cmd.otherOptions.customizedSync",
"cmd.otherOptions.downloadCustomFile",
"cmd.otherOptions.joinCommunity",
"cmd.otherOptions.openIssue",
"cmd.otherOptions.releaseNotes"
```

What do you think?

**Comment by shanalikhan** [comment]
Yes `IsConfigured()` is fine.

> I was also thinking of removing some items

Yes as we have UI now, most of the things can be managed from there. Its safe to remove them.

**Comment by arnohovhannisyan** [comment]
@shanalikhan Since we added the buttons to `Donate` or `Write a Review` in the landing page, maybe we should remove `DonateMessage()` from the codebase. Judging from the community's response to #713, it's clear that `Settings Sync` already has lots of distracting and somewhat annoying pop-ups that could lead to worse user experience. What do you think?

References:
- https://github.com/shanalikhan/code-settings-sync/blob/ebdca4f24d3ba5376283941bbe5041bec1115ecb/src/commons.ts#L336-L346
- https://github.com/shanalikhan/code-settings-sync/blob/ebdca4f24d3ba5376283941bbe5041bec1115ecb/src/commons.ts#L354-L378

**Comment by shanalikhan** [comment]
Lets keep this now, we will look into it later how we can improve it.

**Comment by shanalikhan** [comment]
I suggest you to close this PR.
and rebase your commits into the latest `master` branch and then fix the conflicts. In this way we will be sure that no feature/code is missing from whole code refactoring.

**Comment by shanalikhan** [comment]
@arnohovhannisyan 

Any update on this ?

**Pull request closed without merging**
