### PR TITLE
Improve UX

### PR DESCRIPTION
**Pull request by arnohovhannisyan**
#### Short description of what this resolves:
This PR improves the UX of Settings Sync

#### Changes proposed in this pull request:

- ...https://github.com/shanalikhan/code-settings-sync/pull/960#issuecomment-512782903
- Bind checkbox to state

**Fixes**: https://github.com/shanalikhan/code-settings-sync/pull/960#issuecomment-512782903

#### How Has This Been Tested?

- Download without config (no skip button, download initiated after gist selected)
- Upload without config (skip button, upload initiated after gist selected or skipped)
- Checkbox binding checked by changing the state and reopening the page

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.

### CODE REVIEW

**Comment by shanalikhan** [comment]
@arnohovhannisyan Thanks, okay let me go with one by one as discussed.


1. On Startup
     When user click on Login with Github and click on `skip` button. - **Done**


2. On Upload - See Comment
    When token and GIST is not configured, page does open along with the warning of invalid GIST.
     - Invalid GIST error should not appear when GIST is empty. - **Done**
     - When user gets the token and select any gist. It should start the upload process automatically as User is coming from `On Upload` process. - **Done**
     - If user click on `Skip` button, it should start the upload process create the new GIST as User is coming from `On Upload` Process. - **Done**
    **Comments:** If there is no Gist found or the list is empty, there should be message similar to "To Gist attached with your account, Skip this window and upload the settings to create new Gist"


3. On Download - See comment First is show stopping
    When token and GIST is not configured, page does open along with Invalid GIST error.
    - Invalid GIST error should not appear when GIST is empty - **Done**
    - When user gets the token
    - On Gist Page, `Skip` button should be hidden as user wants to download, instead we can show close button to stop the process - **Done**
    - When user select any GIST, it should start downloading process as user is coming from `On Download` process
       **Comments** : 
                          1. If there is no GIST found or the list is empty, there should be message similar to  "No Gist attached with your account. Skip this window and upload the settings to create new Gist"
                          2. When user selects the GIST, the tab is automatically switched to Welcome Page hence download is stopped. I had to go to that tab and click on the code model button in order to initiate the download process.

4. New Github user.
    If there is no GIST available to Github user attached. Login to Github does not show anything that it has fetched the token. We need to show that screen everytime even there is no GIST attached. ( tried to new github account).
    **Comments:** If there is no Gist found or the list is empty, there should be message similar to "To Gist attached with your account, Skip this window and upload the settings to create new Gist"


What are your thoughts?

Thanks, i have got the application access.

**Comment by shanalikhan** [comment]
@arnohovhannisyan when can you fix the improvements mentioned.

**Comment by arnohovhannisyan** [comment]
@shanalikhan I'm not sure. If I have time, I'll fix the things you mentioned tomorrow.

**Comment by shanalikhan** [comment]
alright.

**Pull request merged**
