### PR TITLE
Korean translating update

### PR DESCRIPTION
**Pull request by mijien0179**
fixing some wrong translate.

#### Short description of what this resolves:
Just fixing some mistake translate

#### Changes proposed in this pull request:

- package.nls.ko.json fixing
-
-

**Fixes**: #

#### Checklist:

- [X] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [X] My change requires a change to the documentation and GitHub Wiki.
- [X] I have updated the documentation and Wiki accordingly.

### CODE REVIEW

**Comment by shanalikhan** [comment]
Can you start the keys with `Sync: `

We need to make standard consistent across all languages. You can the `Sync :` prefix on the keys in the following file.
https://github.com/shanalikhan/code-settings-sync/blob/master/package.nls.zh-cn.json

**Comment by mijien0179** [comment]
I'm completed your request. but this translating may be mistake in some case. because I'm not sure where do its using per each item.

**Comment by shanalikhan** [comment]
I have updated the branch. Someone from the last week also improved the korean language.
Can you resolve the conflicts?

**Comment by mijien0179** [comment]
solve

**Pull request merged**
