### PR TITLE
[WIP] - [EXPERIMENTAL] Multiple instance support

### PR DESCRIPTION
**Pull request by arnohovhannisyan**
#### Short description of what this resolves:
This PR fixes issues with multiple instances running at the same time.

#### Changes proposed in this pull request:

- Only allow one instance of VS Code to auto-upload
- Catch errors with lock file

**Fixes**: #839 

#### How Has This Been Tested?

I have tested it by installing it and running multiple instances of VS Code. However, I could have missed something, so it needs a lot more testing before even thinking about merging it.

#### Checklist:

- [x] I have read the [contribution](https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#setup-extension-locally) guidelines.
- [x] Auto upload only from the first instance of VS Code
- [x] Somehow update configuration when the auto upload instance is closed
- [ ] Lots of testing

### CODE REVIEW

**Comment by k1nghat** [comment]
would it be possible to signal the other instances that there has been an update and to trigger a download on the other instances?

**Comment by arnohovhannisyan** [comment]
@k1nghat This PR only has to do with auto upload. Downloading is not affected by any of the changes proposed here.

**Comment by shanalikhan** [comment]
@arnohovhannisyan do you think we can improve further on this PR ? Or should i go ahead and merge it.

**Comment by arnohovhannisyan** [comment]
@shanalikhan it definitely needs more work.

**Comment by shanalikhan** [comment]
> it definitely needs more work.

What do you suggest, can we include this in release of `v3.3.0` if you can complete the rest of the work by testing.

**Comment by arnohovhannisyan** [comment]
@shanalikhan If there are no issues after testing, then yes.

**Comment by arnohovhannisyan** [comment]
@shanalikhan I'm going to open a new PR with these changes because this one currently has old code from v3.2.9.

**Pull request closed without merging**
